resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/atolkachevsoftteco/board-game-store.git

jobs:
  - name: game-store-job
    plan:
      - get: repo
        trigger: true
      - task: game-store-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gradle
          inputs:
            - name: repo
          outputs:
            - name: build-output
          run:
            path: ./repo/build.sh


      - task: read-the-artifact
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          # To receive "the-artifact", specify it as an input
          inputs:
            - name: build-output
          run:
            path: sh
            args:
              - -cx
              - |
                cd /build-output
                ls -l .